In [110]:
import cv2
import numpy as np
# Loading source image
src_image = cv2.imread("apic.jpg")
#src_image = cv2.cvtColor(src_image, cv2.COLOR_BGR2GRAY)

# src_image = np.array([
#   [1,1,1,0,0,1,1,0,0],
#   [0,1,1,1,0,1,1,0,0],
#   [0,0,1,1,1,1,1,0,0],
#   [0,0,1,1,0,1,1,0,0],
#   [0,1,1,0,0,1,1,0,0],
#   [0,1,1,0,0,1,1,0,0],
#   [0,1,1,0,0,1,1,0,0],
#   [0,1,1,0,0,1,1,0,0]
# ])
# Defining the kernel of size 3x3
#[255, 255, 0,0],
#[1, 1, 0,0],
kernel = np.array([
  [25, 25, 0,0],
  [25, 25, 0,0],
  [25, 25, 0,0],
  [25, 25, 0,0]
])

In [111]:
resulting_image = cv2.filter2D(src_image, -1, kernel)
 
cv2.imshow("original image", src_image)
cv2.imshow("filter2d image", resulting_image)
#cv2.imwrite("Filter2d Sharpened Image.jpg", resulting_image)
cv2.waitKey()
cv2.destroyAllWindows()

In [104]:
print(src_image)

[[255 255 255 ...  46 208 255]
 [255 255 255 ...  49 207 255]
 [255 255 255 ...  48 208 255]
 ...
 [213 213 213 ...  33 166 202]
 [251 251 251 ...  43 204 247]
 [255 255 255 ...  41 204 248]]


In [105]:
print(resulting_image)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [57]:
print(src_image+21)

[[ 20  20  20 ...  67 229  20]
 [ 20  20  20 ...  70 228  20]
 [ 20  20  20 ...  69 229  20]
 ...
 [234 234 234 ...  54 187 223]
 [ 16  16  16 ...  64 225  12]
 [ 20  20  20 ...  62 225  13]]


In [32]:
import cv2
import numpy as np
# Loading source image
src_image = cv2.imread("chica.png")
src_image = cv2.cvtColor(src_image, cv2.COLOR_BGR2GRAY)
# Defining the Sobel kernel of size 3x3
# kernel = np.array([
#   [1/9, 1/9, 1/9],
#   [1/9, 1/9, 1/9],
#   [1/9, 1/9, 1/9]
# ])
kernel = np.array([
  [0, 1, 0],
  [1, -4, 1],
  [0, 1, 0],
])

In [33]:
resulting_image = cv2.filter2D(src_image, -1, kernel)
 
cv2.imshow("original image", src_image)
cv2.imshow("filter2d image", resulting_image)
#cv2.imwrite("Filter2d Sobel Image.jpg", resulting_image)
cv2.waitKey()
cv2.destroyAllWindows()